# SELECT * FROM ANIMAL_INS; 보호 시작일

# SELECT * FROM ANIMAL_OUTS; 입양일

SELECT 
    I.ANIMAL_ID,
    I.NAME 
FROM 
    ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE 
    O.DATETIME < I.DATETIME 
ORDER BY I.DATETIME ASC;

# 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름 조회 단 보호 시작일이 빠른 순