SELECT FI.ID, FN.FISH_NAME, FI.LENGTH 
FROM FISH_INFO FI 
INNER JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE 
WHERE (FI.FISH_TYPE, FI.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) 
AND FI.LENGTH >= 10 
ORDER BY FI.ID ASC;


# 테이블 FISH_INFO 
# 테이블 FISH_NAME_INFO
# FISH_TYPE 칼럼으로 조인