# SELECT * FROM HR_EMPLOYEES;

# SELECT * FROM HR_GRADE;

SELECT 
    SUM(G.SCORE) AS SCORE, 
    E.EMP_NO, 
    E.EMP_NAME, 
    E.POSITION, 
    E.EMAIL
FROM 
    HR_EMPLOYEES E
INNER JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR = 2022
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SCORE DESC
LIMIT 1;